-- ------------------------------- Topics In SQL ------------------------------------------

-- USE
-- SELECT Clause
-- FROM
-- WHERE Clause
-- ORDER BY Clause
-- LIMIT
-- INNER JOIN
-- Multiple Table Join 
-- Join Across Diffrent Databases
-- Inner Self Join
-- Compounds join conditions
-- Outer Join
-- Muiltiple Outer Join
-- Self Outer Join
-- Using Clause
-- Natural Joins
-- Cross Joins
-- Union
-- Insert a Single Row
-- Insert Multiple Row
-- Insert Hirearcial Rows
-- Creating a Copy of Table